############   Stage-I (Build)  ###############################
FROM node:18-alpine as build

WORKDIR /app

# ✅ Declare build arguments
ARG USER_POOL_ID
ARG CLIENT_ID
ARG API_BASE_URL

# ✅ Convert them to env (so React can use them)
ENV REACT_APP_USER_POOL_ID=$USER_POOL_ID
ENV REACT_APP_CLIENT_ID=$CLIENT_ID
ENV REACT_APP_API_BASE_URL=$API_BASE_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

##############  Stage - II (Serve with Nginx)  ##################

#FROM nginx:alpine
#COPY --from=build /app/build /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]

FROM nginx:1.24.0-alpine3.17-slim

# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/cache/nginx/client_temp && \
    mkdir -p /var/cache/nginx/proxy_temp && \
    mkdir -p /var/cache/nginx/fastcgi_temp && \
    mkdir -p /var/cache/nginx/uwsgi_temp && \
    mkdir -p /var/cache/nginx/scgi_temp && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /etc/nginx/ && \
    chmod -R 755 /etc/nginx/ && \
    chown -R nginx:nginx /var/log/nginx

RUN mkdir -p /etc/nginx/ssl/ && \
    chown -R nginx:nginx /etc/nginx/ssl/ && \
    chmod -R 755 /etc/nginx/ssl/

RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid /run/nginx.pid
# COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html
USER nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# FROM nginx:1.24.0
# RUN rm -f /usr/share/nginx/html/index.html
# RUN rm -f /etc/nginx/nginx.conf
# RUN rm -f /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY static /usr/share/nginx/html/

# docker build \
#  --build-arg USER_POOL_ID=your_pool_id \
#  --build-arg CLIENT_ID=your_client_id \
#  --build-arg API_BASE_URL=your_api_base_url \
#  -t your-image .




